### ISSUE TITLE
Trouble using the package with AoT

### ISSUE THREAD

**Issue by Charkhan** [flauc/angular2-notifications#82]
Hi @flauc,

Decided to build my angular 2 project with AoT technique (https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)

But got the following error on compilation:

```
Error: Unexpected value 'SimpleNotificationsModule' imported by the module 'AppModule'
```

Metadata needs to be generated for each component, to let ngc "see" your classes.

Here is a helpful discussion: https://github.com/michaelbromley/ng2-pagination/issues/74

Thanks for the package btw !

**Comment by flauc** [comment]
Hi @Charkhan,

Thank you for reporting this 👍 
I haven't really tried the library with AoT yet so I'm not sure what's required to get it to work. I'll look in to it now.

**Comment by Charkhan** [comment]
Thank you for the quick answer ! I'll stay tuned for your update :+1:

**Comment by bkotyik** [comment]
You should ship metadata.json files to support aot compilation.
See: https://github.com/angular/angular/issues/11262#issuecomment-244489405

**Comment by montella1507** [comment]
I have to say i can't wait for AOT support for your awesome library...

**Comment by flauc** [comment]
Thank you for the support 👍 

I'm sorry i couldn't implement this yet I've been awfully busy last week. I'll try to have this resolved in the next few days. 

Also if any one is willing to do a pr it would be greatly appreciated :)

**Comment by montella1507** [comment]
Unfortunately i think i dont have enough of experience with ng2/npm dev cykle.. so i can be only your morale support :-/ 

![tpcko](https://cloud.githubusercontent.com/assets/10418323/19249889/fdf7d0da-8f37-11e6-9e62-f21f60eb3923.png)

**Comment by bkotyik** [comment]
I forked your repo @flauc and added AoT support to the library. 
All the neccessary metadata files and ngFactory classes gets generated, but in my project somehow it does not work. I still get the same message as @Charkhan . 

Can you try it guys so that we could find out whats wrong with it.

Here can you find it: https://github.com/bkotyik/angular2-notifications

**Comment by Charkhan** [comment]
@bkotyik 

Comparing to : https://github.com/michaelbromley/ng2-pagination/

He didn't gitignore the metadata.json files, and also have declarations files (*.d.ts). Basically, he just included in its tsconfig two files ("src/ng2-pagination" and "typings/index.d.ts")

That might be enough. I'm no JS/TS expert but from my experience tbh.

**Comment by bkotyik** [comment]
Ignoring the d.ts and metadata.json files is okay. These files are artifacts that are created during the compile phase, so I think they should not be version controlled by git.

What you need to do in case of my fork:
1) Clone repo
2) run "npm install" to install all the needed dependencies
3) run "npm run ts" to compile the source code and create metadata.json files and ngFactory classes.
4) the build will be available under the "lib" directory, you can rewrite your import statements temporarily to grab the components from it.

Note that, the third step needed only when you use the source code to create the build.  (So your lib folder is empty or does not exist.)
When you install a library via npm, the source code is already built and you have the metadata.json and ngFactory files by default. (So you have the lib folder with all the neccessary files.)

**Comment by Charkhan** [comment]
@bkotyik 

How could I change my import statements ? I actually have in my app.module.ts:
```
import {SimpleNotificationsModule} from "angular2-notifications/components";
```

**Comment by montella1507** [comment]
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.g7ef4ekx3 here should be the way how to build

**Comment by flauc** [comment]
Hey @montella1507, 

Thanks for the link 👍 
I'll try this approach tomorrow.

**Comment by Charkhan** [comment]
Hey @flauc !

Any progress on this ? I tried on my own to get it working, but with no luck....

**Comment by oneschilling** [comment]
Hey @flauc 
I am also interested in this fix. Were you able to make any progress?

**Comment by michalstepien** [comment]
Hi, any news?

**Comment by flauc** [comment]
I've just added ngc compilation and now the lib folder includes the metadata.json files. I don't know if this is enough. I didn't have the time to do some more research in to AoT. I'll try to do some more work on this over the weekend. 

Any help is greatly appreciated 👍

**Comment by fbobbio** [comment]
@flauc I did try the same in my local, including the *metadata.json* files in _lib_ folder.

I noticed that you have a gulp task packing all your sources into a components.d.ts
Probably that's what should be seen by the AOT compiler, but I couldn't figure out how.

So when using angular2-notifications from my project, and trying to compile my project with ngc, I get the error: `Error: Unexpected value 'SimpleNotificationsModule' imported by the module 'YYYModule'`

Did you tried compiling with ngc a project that uses your package?
I'll let you know if I go deeper, thanks for the work.

**Comment by flauc** [comment]
I simply can't get this working: 

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

Are you maybe using a starter with AoT? Could you share the link if you are? 

Thanks for the support 👍

**Comment by michalstepien** [comment]
I think we have to change components.js to ts and generate metadata for this file to. I will check this today.

**Comment by michalstepien** [comment]
Ok it works, so chang components.js to componets.ts with:
`export { SimpleNotificationsModule } from './src/simple-notifications.module';
export { SimpleNotificationsComponent } from './src/simple-notifications.component';
export { NotificationComponent } from './src/notification.component';
export { NotificationsService } from './src/notifications.service';
export { MaxPipe } from './src/max.pipe';
export { PushNotificationsModule } from './src/push-notifications.module';
export { PushNotificationsService } from './src/push-notifications.service';`

**Comment by michalstepien** [comment]
and change to   `"files": [ "components.ts", ` in tsconfig.aot

**Comment by michalstepien** [comment]
"outDir": "./lib", should be src

**Comment by flauc** [comment]
Great work man, I'll implement this later today 👍, or send a PR if you feel like it.

**Comment by flauc** [comment]
Are you sure that the outDir should be src? If i do that i get a lib folder with a src sub folder.

**Comment by fbobbio** [comment]
Great job guys!

I think outDir is ok. That is the destination folder of the compiled files and we don't want them on the src folder.

Are you planning to tag and release current version? For some strange reason I can not see the tags.

**Comment by flauc** [comment]
There is still a problem. If i set the outDir to be lib, the lib folder ends up with a src sub folder. Try cloning the repo and running `npm run tsc:aot`

**Comment by michalstepien** [comment]
[angular2-notifications.zip](https://github.com/flauc/angular2-notifications/files/560692/angular2-notifications.zip)

**Comment by michalstepien** [comment]
Hmm, sory my mistake :) "outDir": "./lib" is good.

**Comment by flauc** [comment]
I think i finally got this resolved. I'm pretty confident that this is it. Can anyone who is interested please test it out in there environments? 

It's working for me, but there are so many different setups i can't be sure that this is optimal.

**Comment by michalstepien** [comment]
hi @flauc , could you change this: In notification.component.ts in template should be (click)="onClick($event)" not (click)="onClick($e)"

**Comment by jebright** [comment]
Trying to figure out the status of this - is this fixed?  Sounds like you needed someone to help you test this out?

**Comment by anasAsh** [comment]
i just tested version 0.4.46, it's working as expected.

**Comment by flauc** [comment]
Should not be an issue with the latest release.
